#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_auth_login:
  path: /api/auth/login
  methods:  [POST]

api:
  prefix: /api
  type: annotation
  resource: '../src/Controller/Api/'